# Service definition
name: core
description: Entry point for all services, used for service discovery and runtime tuning updates

# No dependencies
dependencies: []

# Outputs
outputs:
  # request/reply model
  - name: server
    address: tcp://*:1337
  # pub/sub model
  - name: broadcast
    address: tcp://*:1338
